In [4]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv('/content/students_data.csv')

In [6]:
#Display the first 10 rows of the DataFrame.
df.iloc[:11]

    StudentID     Name  Gender  Grade  Attendance           Subject
0         1.0  Charlie    Male   69.0         NaN           English
1         2.0    Frank       M   55.0        71.0           Physics
2         3.0  Charlie    Male   75.0        97.0              Math
3         4.0    Alice    male   46.0        59.0           Biology
4         5.0     Noah    Male   47.0        86.0              Math
5         6.0    Alice       F   87.0        70.0           Biology
6         7.0    Karen  female   71.0        61.0           Physics
7         8.0    Frank    male   82.0        95.0           Physics
8         9.0      Bob    Male   82.0        52.0           English
9        10.0    Henry       M   56.0        86.0  Computer Science
10       11.0    David       M   83.0        51.0  Computer Science

In [7]:
#Get a summary of the DataFrame, including:
#Data types of columns. Shape of the DataFrame.
#Basic statistics using .describe().
df.dtypes

StudentID     float64
Name           object
Gender         object
Grade         float64
Attendance    float64
Subject        object
dtype: object

In [8]:
df.shape

(1000, 6)

In [9]:
df.describe()

         StudentID       Grade  Attendance
count   968.000000  955.000000  948.000000
mean    499.685950   65.568586   75.353376
std     288.515855   15.417402   14.733558
min       1.000000   12.000000   50.000000
25%     250.750000   55.000000   62.000000
50%     498.500000   65.000000   75.000000
75%     750.250000   76.000000   88.000000
max    1000.000000  113.000000  100.000000

In [10]:
df.isnull()

     StudentID   Name  Gender  Grade  Attendance  Subject
0        False  False   False  False        True    False
1        False  False   False  False       False    False
2        False  False   False  False       False    False
3        False  False   False  False       False    False
4        False  False   False  False       False    False
..         ...    ...     ...    ...         ...      ...
995      False  False   False  False       False    False
996      False  False   False  False       False    False
997      False  False   False  False       False    False
998      False  False   False  False       False    False
999      False  False   False  False       False    False

[1000 rows x 6 columns]

In [11]:
df.isnull().sum()

StudentID     32
Name          18
Gender         0
Grade         45
Attendance    52
Subject        0
dtype: int64

In [12]:
#Replace missing Grade values with the column's mean.
df['Grade'].fillna(df['Grade'].mean(), inplace=True)

<ipython-input-12-43425b5d3dd8>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Grade'].fillna(df['Grade'].mean(), inplace=True)

In [13]:
#David went from null to the average
df.iloc[:23]

    StudentID     Name  Gender      Grade  Attendance           Subject
0         1.0  Charlie    Male  69.000000         NaN           English
1         2.0    Frank       M  55.000000        71.0           Physics
2         3.0  Charlie    Male  75.000000        97.0              Math
3         4.0    Alice    male  46.000000        59.0           Biology
4         5.0     Noah    Male  47.000000        86.0              Math
5         6.0    Alice       F  87.000000        70.0           Biology
6         7.0    Karen  female  71.000000        61.0           Physics
7         8.0    Frank    male  82.000000        95.0           Physics
8         9.0      Bob    Male  82.000000        52.0           English
9        10.0    Henry       M  56.000000        86.0  Computer Science
10       11.0    David       M  83.000000        51.0  Computer Science
11       12.0     Noah    male  78.000000        79.0           Science
12       13.0    Karen    Male  40.000000        79.0           Science
13       14.0    Frank       M  50.000000        55.0  Computer Science
14       15.0    Alice  Female  65.000000        91.0           Physics
15       16.0      Bob    Male  69.000000        83.0         Chemistry
16       17.0    Karen  Female  75.000000        59.0           Biology
17       18.0      Bob  female  69.000000        55.0           Biology
18       19.0    Alice       M  63.000000        88.0         Chemistry
19       20.0    Alice       M  96.000000        79.0           English
20       21.0      Eve  female  77.000000         NaN           English
21       22.0     Noah    Male  98.000000        88.0         Chemistry
22       23.0    David       F  65.568586        99.0           History

In [14]:
#Fill missing Attendance values with a constant value (e.g., 0).
df.fillna({'Attendance':0}, inplace=True)

In [15]:
#Charlie went from null to 0
df.iloc[:1]

   StudentID     Name Gender  Grade  Attendance  Subject
0        1.0  Charlie   Male   69.0         0.0  English

In [16]:
#Drop any rows where the Name or StudentID is missing.
df.dropna(subset=['Name', 'StudentID'], inplace=True)
#Grace and Mia are removed
df.iloc[60:65]

    StudentID   Name Gender      Grade  Attendance           Subject
60       61.0    Bob      M  55.000000        98.0           History
61       62.0  Henry   Male  73.000000        83.0  Computer Science
62       63.0    Eve   male  35.000000        79.0           Physics
65       66.0  Alice      M  65.568586        81.0         Chemistry
66       67.0  David   male  61.000000        58.0           Science

In [17]:
#Standardize the Gender column to ensure values are consistent (e.g., replace "M" with "Male" and "F" with "Female").
df['Gender'].replace({'M':'Male', 'F': 'Female', 'male': 'Male', 'female' : 'Female'}, inplace=True)
df.iloc[:23]

<ipython-input-17-01aa325da6c7>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gender'].replace({'M':'Male', 'F': 'Female', 'male': 'Male', 'female' : 'Female'}, inplace=True)

    StudentID     Name  Gender      Grade  Attendance           Subject
0         1.0  Charlie    Male  69.000000         0.0           English
1         2.0    Frank    Male  55.000000        71.0           Physics
2         3.0  Charlie    Male  75.000000        97.0              Math
3         4.0    Alice    Male  46.000000        59.0           Biology
4         5.0     Noah    Male  47.000000        86.0              Math
5         6.0    Alice  Female  87.000000        70.0           Biology
6         7.0    Karen  Female  71.000000        61.0           Physics
7         8.0    Frank    Male  82.000000        95.0           Physics
8         9.0      Bob    Male  82.000000        52.0           English
9        10.0    Henry    Male  56.000000        86.0  Computer Science
10       11.0    David    Male  83.000000        51.0  Computer Science
11       12.0     Noah    Male  78.000000        79.0           Science
12       13.0    Karen    Male  40.000000        79.0           Science
13       14.0    Frank    Male  50.000000        55.0  Computer Science
14       15.0    Alice  Female  65.000000        91.0           Physics
15       16.0      Bob    Male  69.000000        83.0         Chemistry
16       17.0    Karen  Female  75.000000        59.0           Biology
17       18.0      Bob  Female  69.000000        55.0           Biology
18       19.0    Alice    Male  63.000000        88.0         Chemistry
19       20.0    Alice    Male  96.000000        79.0           English
20       21.0      Eve  Female  77.000000         0.0           English
21       22.0     Noah    Male  98.000000        88.0         Chemistry
22       23.0    David  Female  65.568586        99.0           History

In [18]:
def pass_fail(grade):
  if grade >= 50:
    return 'Pass'
  else:
    return 'Fail'

In [19]:
#Add a new column called Pass/Fail:
#A student passes if their Grade is 50 or above.

df['Pass/Fail'] = df['Grade'].apply(pass_fail)
df

     StudentID     Name  Gender  Grade  Attendance    Subject Pass/Fail
0          1.0  Charlie    Male   69.0         0.0    English      Pass
1          2.0    Frank    Male   55.0        71.0    Physics      Pass
2          3.0  Charlie    Male   75.0        97.0       Math      Pass
3          4.0    Alice    Male   46.0        59.0    Biology      Fail
4          5.0     Noah    Male   47.0        86.0       Math      Fail
..         ...      ...     ...    ...         ...        ...       ...
995      996.0     Jack    Male   77.0        60.0  Chemistry      Pass
996      997.0  Charlie    Male   63.0        71.0    Science      Pass
997      998.0     Noah  Female   51.0        79.0       Math      Pass
998      999.0  Charlie    Male   52.0        73.0    English      Pass
999     1000.0    Frank  Female   54.0        62.0       Math      Pass

[950 rows x 7 columns]

In [20]:
#Create a new DataFrame containing only students who have Attendance greater than 75%.

attendance_df = df[df['Attendance'] > 75]

#Sort the DataFrame by Grade in descending order.
attendance_df.sort_values(by='Attendance', ascending=False, inplace=True)
attendance_df

<ipython-input-20-48ac17908a38>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df.sort_values(by='Attendance', ascending=False, inplace=True)

     StudentID    Name  Gender  Grade  Attendance           Subject Pass/Fail
74        75.0   David    Male   60.0       100.0              Math      Pass
165      166.0   Frank  Female   59.0       100.0           History      Pass
579      580.0     Bob    Male   66.0       100.0           History      Pass
251      252.0    Jack    Male   98.0       100.0           Physics      Pass
497      498.0    Jack  Female   70.0       100.0           Physics      Pass
..         ...     ...     ...    ...         ...               ...       ...
799      800.0  Olivia    Male   66.0        76.0           Physics      Pass
280      281.0     Eve  Female   85.0        76.0           Physics      Pass
896      897.0    Noah    Male   40.0        76.0  Computer Science      Fail
971      972.0     Eve  Female   79.0        76.0           History      Pass
44        45.0   David  Female   87.0        76.0         Chemistry      Pass

[451 rows x 7 columns]

In [25]:
#Group the data by Subject and calculate the average Grade for each subject.

df_subject = df.groupby('Subject').describe()
df_subject

                 StudentID                                               \
                     count        mean         std   min     25%    50%
Subject
Biology              119.0  473.873950  291.874699   4.0  225.50  447.0
Chemistry            115.0  519.669565  291.655580  16.0  260.50  540.0
Computer Science     110.0  461.136364  283.355467  10.0  193.50  471.5
English              121.0  501.371901  274.092233   1.0  274.00  507.0
History              127.0  528.787402  292.255396  23.0  284.50  554.0
Math                 101.0  490.306931  294.626229   3.0  226.00  464.0
Physics              113.0  519.097345  292.645811   2.0  292.00  537.0
Science              144.0  494.604167  294.731885  12.0  216.75  469.0

                                  Grade             ...                \
                     75%     max  count       mean  ...    75%    max
Subject                                             ...
Biology           711.00   995.0  119.0  64.859448  ...  74.00  101.0
Chemistry         757.00   996.0  115.0  67.698038  ...  77.00  107.0
Computer Science  686.75   991.0  110.0  64.568805  ...  73.75  100.0
English           730.00   999.0  121.0  65.432019  ...  75.00  106.0
History           805.50   989.0  127.0  65.031339  ...  75.00  101.0
Math              716.00  1000.0  101.0  65.340708  ...  76.00  107.0
Physics           783.00   992.0  113.0  66.223491  ...  72.00  108.0
Science           774.00   997.0  144.0  65.190358  ...  76.25  103.0

                 Attendance                                               \
                      count       mean        std  min   25%   50%   75%
Subject
Biology               119.0  69.529412  22.409450  0.0  59.5  72.0  85.0
Chemistry             115.0  71.808696  21.178811  0.0  60.0  74.0  87.5
Computer Science      110.0  74.454545  20.420639  0.0  63.5  78.0  90.0
English               121.0  71.330579  20.831222  0.0  60.0  73.0  87.0
History               127.0  70.299213  26.760346  0.0  61.0  77.0  90.5
Math                  101.0  68.693069  24.069376  0.0  57.0  70.0  86.0
Physics               113.0  74.000000  19.491298  0.0  63.0  75.0  88.0
Science               144.0  72.534722  19.488535  0.0  60.0  74.0  87.0


                    max
Subject
Biology            99.0
Chemistry          99.0
Computer Science   99.0
English            99.0
History           100.0
Math              100.0
Physics           100.0
Science            99.0

[8 rows x 24 columns]

In [32]:
#Find the top 3 students with the highest grades in each subject.

top_three = df.groupby('Subject').apply(lambda x: x.nlargest(3,'Grade'))
top_three

<ipython-input-32-182be1e9cbb0>:3: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  top_three = df.groupby('Subject').apply(lambda x: x.nlargest(3,'Grade'))

                      StudentID     Name  Gender  Grade  Attendance  \
Subject
Biology          994      995.0    Karen  Female  101.0        58.0
                 860      861.0    Henry  Female   98.0         0.0
                 494      495.0     Liam  Female   92.0        69.0
Chemistry        926      927.0  Charlie  Female  107.0        72.0
                 739      740.0     Liam    Male  101.0        60.0
                 734      735.0    Karen    Male  100.0         0.0
Computer Science 563      564.0      Eve    Male  100.0        93.0
                 141      142.0   Olivia    Male   89.0        55.0
                 873      874.0   Olivia  Female   88.0        80.0
English          844      845.0      Bob    Male  106.0        54.0
                 977      978.0    Henry    Male   98.0        61.0
                 19        20.0    Alice    Male   96.0        79.0
History          353      354.0    Alice    Male  101.0        87.0
                 657      658.0     Jack    Male   94.0        64.0
                 877      878.0      Ivy  Female   94.0        85.0
Math             198      199.0     Jack    Male  107.0         0.0
                 715      716.0     Noah    Male  107.0        97.0
                 939      940.0     Jack  Female  101.0        66.0
Physics          36        37.0   Olivia    Male  108.0        59.0
                 275      276.0      Mia    Male  103.0        78.0
                 846      847.0    Henry  Female  101.0        75.0
Science          274      275.0     Jack    Male  103.0        63.0
                 840      841.0    David    Male  102.0        76.0
                 786      787.0     Liam    Male   97.0        74.0

                               Subject Pass/Fail
Subject
Biology          994           Biology      Pass
                 860           Biology      Pass
                 494           Biology      Pass
Chemistry        926         Chemistry      Pass
                 739         Chemistry      Pass
                 734         Chemistry      Pass
Computer Science 563  Computer Science      Pass
                 141  Computer Science      Pass
                 873  Computer Science      Pass
English          844           English      Pass
                 977           English      Pass
                 19            English      Pass
History          353           History      Pass
                 657           History      Pass
                 877           History      Pass
Math             198              Math      Pass
                 715              Math      Pass
                 939              Math      Pass
Physics          36            Physics      Pass
                 275           Physics      Pass
                 846           Physics      Pass
Science          274           Science      Pass
                 840           Science      Pass
                 786           Science      Pass

In [37]:
#Create a pivot table showing the average Grade of students for each Subject
#and Gender.

df.pivot_table(index= 'Subject',
               columns='Gender',
               values='Grade',
               aggfunc='mean')

Gender               Female       Male
Subject
Biology           66.871872  62.945996
Chemistry         69.806021  65.697240
Computer Science  63.705882  65.314722
English           65.685559  65.220736
History           64.242858  65.673388
Math              64.677609  65.832316
Physics           65.507621  66.878694
Science           66.510906  63.905989